
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// LEAGUE
export const CREATE_LEAGUE_SUCCESS = "CREATE_LEAGUE_SUCCESS";
export const DELETE_LEAGUE_SUCCESS = "DELETE_LEAGUE_SUCCESS";
export const GET_LEAGUE_SUCCESS = "GET_LEAGUE_SUCCESS";
export const LIST_LEAGUE_SUCCESS = "LIST_LEAGUE_SUCCESS";
export const UPDATE_LEAGUE_SUCCESS = "UPDATE_LEAGUE_SUCCESS";

// MATCHES
export const CREATE_MATCHES_SUCCESS = "CREATE_MATCHES_SUCCESS";
export const DELETE_MATCHES_SUCCESS = "DELETE_MATCHES_SUCCESS";
export const GET_MATCHES_SUCCESS = "GET_MATCHES_SUCCESS";
export const LIST_MATCHES_SUCCESS = "LIST_MATCHES_SUCCESS";
export const UPDATE_MATCHES_SUCCESS = "UPDATE_MATCHES_SUCCESS";

// PLAYERS
export const CREATE_PLAYERS_SUCCESS = "CREATE_PLAYERS_SUCCESS";
export const DELETE_PLAYERS_SUCCESS = "DELETE_PLAYERS_SUCCESS";
export const FINDBYNAME_PLAYERS_SUCCESS = "FINDBYNAME_PLAYERS_SUCCESS";
export const GET_PLAYERS_SUCCESS = "GET_PLAYERS_SUCCESS";
export const LIST_PLAYERS_SUCCESS = "LIST_PLAYERS_SUCCESS";
export const UPDATE_PLAYERS_SUCCESS = "UPDATE_PLAYERS_SUCCESS";

// PREFERENCES
export const CREATE_PREFERENCES_SUCCESS = "CREATE_PREFERENCES_SUCCESS";
export const DELETE_PREFERENCES_SUCCESS = "DELETE_PREFERENCES_SUCCESS";
export const GET_PREFERENCES_SUCCESS = "GET_PREFERENCES_SUCCESS";
export const LIST_PREFERENCES_SUCCESS = "LIST_PREFERENCES_SUCCESS";
export const UPDATE_PREFERENCES_SUCCESS = "UPDATE_PREFERENCES_SUCCESS";

// TEAMS
export const CREATE_TEAMS_SUCCESS = "CREATE_TEAMS_SUCCESS";
export const DELETE_TEAMS_SUCCESS = "DELETE_TEAMS_SUCCESS";
export const FINDBYNAME_TEAMS_SUCCESS = "FINDBYNAME_TEAMS_SUCCESS";
export const GET_TEAMS_SUCCESS = "GET_TEAMS_SUCCESS";
export const LIST_TEAMS_SUCCESS = "LIST_TEAMS_SUCCESS";
export const UPDATE_TEAMS_SUCCESS = "UPDATE_TEAMS_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
